<?php

namespace QQ\Module\Vpgov\Controller;

use Phalcon\Di\Service;
use QQ\Core\Model\Services\Service\Workflow;


class BackendController extends ControllerBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

    }

    public function indexAction()
    {
    $this->view->setVar('title','Backend');
    }

    public function slideAction()
    {
        $this->assets->addJs("/modules/vpgov/themes/backend/default/ng-app/app.js");
        $this->assets->addJs("/modules/vpgov/themes/backend/default/ng-app/upload/services/index.js");
        $this->assets->addJs("/modules/vpgov/themes/backend/default/ng-app/upload/controllers/popup.js");
        $this->assets->addJs("/modules/vpgov/themes/backend/default/ng-app/slide/services/index.js");
        $this->assets->addJs("/modules/vpgov/themes/backend/default/ng-app/slide/controllers/index.js");

        $this->view->setVar('main_title', ['vi'=>'Quan tâm của Đảng và Nhà nước']);
        $this->view->setVar('main_breadcrumb', [
            ['title' => ['vi'=>'Trang chủ'], 'href' => '/vpgov/backend/slide'],
            ['title' => ['vi'=>'Quan tâm của Đảng và Nhà nước'], 'href' => false],
        ]);
    }
}
