<?php

namespace QQ\Module\Vpgov\Controller;

use Phalcon\Di\Service;
use QQ\Core\Model\Services\Service\Workflow;
use QQ\Module\Vpgov\Model\SlideEntity;
use QQ\Module\Vpgov\Model\Services\Service\Slide;

class  BackendSlideController extends ControllerBase
{
    private $slide_service;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this-> slide_service = new Slide();
    }

    public function indexAction()
    {
        echo "hi hi hi";
        exit();
    }

    public function saveAction(){

        $uuid = $this->request->getPost('uuid');
        $data = json_decode($this->request->getPost('data'));
        $workflow = json_decode($this->request->getPost('workflow'));

        $m = new SlideEntity();
        $m->assign(array(
            'uuid'  => $uuid,
            'data'  => $data
        ));
        if($m->save()){
            $this->logger->info("Lưu slide thành công");
            echo json_encode(
                array(
                    'success'   => true
                )
            );
        }else{
            echo json_encode(
                array(
                    'success'   => false
                )
            );
        }


        exit();
    }


    public function searchAction(){
        $this->view->disable();
        $r = $this->request;

        $order = $r->getQuery('order') ?: 'asc';
        $page_size = $r->getQuery('page_size') ?: 30;
        $page_number = $r->getQuery('page_number') ?: 1;
        $lang = $r->getQuery('lang') ?: 'vi';

        $items=array();

        if(empty($query)) {
            $filter = array(
                'order' => $order,
                'page_size' => $page_size,
                'page_number' => $page_number,
                'lang'=>$lang,
            );
        }

        $rs = $this->slide_service->filter($filter);

        foreach ($rs as $item){
            $items[]=array(
                'uuid' => $item->uuid,
                'data' => $item->data,
            );
        }
        echo json_encode(array(
            'success' => true,
            'items' => $items,
        ));

        exit();
    }

    public function findByUuidAction(){
        $this->view->disable();
        $r = $this->request;

        $uuid = $r->getQuery('uuid');

        $items=array();

        if(empty($query)) {
            $filter = array(
                'uuid' => $uuid,
            );
        }

        $rs = $this->slide_service->findFirstById($filter);

        foreach ($rs as $item){
            $items[]=array(
                'uuid' => $item->uuid,
                'data' => $item->data,
            );
        }
        echo json_encode(array(
            'success' => true,
            'items' => $items,
        ));

        exit();
    }

    public function listAction(){

        $this->view->disable();
        $r = $this->request;

        $order = $r->getQuery('order') ?: 'asc';
        $page_size = $r->getQuery('page_size') ?: 30;
        $page_number = $r->getQuery('page_number') ?: 1;
        $lang = $r->getQuery('lang') ?: 'vi';

        $items=array();

        if(empty($query)) {
            $filter = array(
                'order' => $order,
                'page_size' => $page_size,
                'page_number' => $page_number,
                'lang'=>$lang,
            );
        }

        $rs = $this->slide_service->filter($filter);

        foreach ($rs as $item){
            $items[]=array(
                'uuid' => $item->uuid,
                'data' => $item->data,
            );
        }
        echo json_encode(array(
            'success' => true,
            'items' => $items,
        ));

        exit();
    }
    public function editAction(){
        $this->view->disable();
        try {
            $m = $this->slide_service->getFirstByUuid($this->request->getQuery('uuid'));
            echo json_encode(array(
                'success'   => true,
                'model'     => $m
            ));
        }catch(Exceptions\EntityNotFoundException $e){
            echo json_encode(array(
                'success'   => false
            ));
        }

        exit();
    }

    public function removeAction(){

        $this->view->disable();
        $uuid = $this->request->getPost('uuid');
        echo "Remove uuid: " ;
        var_dump($uuid);
        try{
            $slide = $this->slide_service->getFirstByUuid($uuid);
            if($slide->delete()){
                echo json_encode(array(
                    'success'   => true
                ));
                exit();
            }
        }catch(Exceptions\EntityNotFoundException $e){

        }

        echo json_encode(array(
            'success'   => false
        ));
        exit();
    }

}
