<?php

namespace QQ\Module\Vpgov\Controller;

use Phalcon\Di\Service;
use QQ\Core\Model\Services\Service\Workflow;
use QQ\Module\Vpgov\Model\SlideEntity;
use QQ\Module\Vpgov\Model\Services\Service\Slide;

class  FrontendSlideController extends ControllerBase
{
    private $slide_service;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this-> slide_service = new Slide();
    }


    public function listAction(){

        $this->view->disable();
        $r = $this->request;

        $order = $r->getQuery('order') ?: 'asc';
        $page_size = $r->getQuery('page_size') ?: 30;
        $page_number = $r->getQuery('page_number') ?: 1;
        $lang = $r->getQuery('lang') ?: 'vi';

        $items=array();

        if(empty($query)) {
            $filter = array(
                'order' => $order,
                'page_size' => $page_size,
                'page_number' => $page_number,
                'lang'=>$lang,
            );
        }

        $rs = $this->slide_service->filter($filter);

        foreach ($rs as $item){
            $items[]=array(
                'uuid' => $item->uuid,
                'data' => $item->data,
            );
        }
        echo json_encode(array(
            'success' => true,
            'items' => $items,
        ));

        exit();
    }
}
