<?php

namespace QQ\Module\Vpgov\Controller;

use Phalcon\Di\Service;
use QQ\Core\Model\Services\Service\Workflow;


class IndexController extends ControllerBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

    }

    public function indexAction()
    {
        $this->view->setVar('title','VP GOV');
        $this->assets->addJs("/modules/vpgov/themes/frontend/default/ng-app/app.js");
        $this->assets->addJs("/modules/vpgov/themes/frontend/default/ng-app/slide/services/index.js");
        $this->assets->addJs("/modules/vpgov/themes/frontend/default/ng-app/slide/controllers/index.js");
    }
}
